import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { useSupabaseClient, useUser } from '@supabase/auth-helpers-react'

export default function Home() {
  const user = useUser()
  const supbase = useSupabaseClient()

  const logOut = () => {
    supbase.auth.signOut()
  }

  return (
    <>
      <Head>
        <title>Prompt Note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="container">
        {user ? (
          <button onClick={logOut}>logout {user.email}</button>
        ) : (
          <p>ログアウト中</p>
        )}
      </div>

      <Footer />
    </>
  )
}
